{
 "title": "Prometheus Ping Exporter",
 "description": "Prometheus Ping Exporter Overview",
 "tags": [
  "prometheus",
  "ping",
  "icmp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": "label_values(probe_success, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Global Probe Duration (Ping Exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ping_rtt_ms{instance=~\"$target\"}/1000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Global Probe Duration (Blackbox Exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$target",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "target",
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_node_status{instance=~\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loss Percent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_packets_loss_percent{instance=~\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "description": "{{label_name}}\nhttp://10.28.28.17:9099/metrics?target=$target",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ping_rtt_ms{instance=~\"$target\"}/1000 # its measuring with seconds ?",
     "legendFormat": "$target RTT milliseconds"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Transmitted",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_packets_transmitted{instance=~\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_packets_received{instance=~\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTT min",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(ping_rtt_ms{instance=~\"$target\"}/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTT max",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ping_rtt_ms{instance=~\"$target\"}/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTT avg",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ping_rtt_ms{instance=~\"$target\"}/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTT current",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_rtt_ms{instance=~\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}